edge_attr:
  "fontsize": "12"
  "fontname": "Helvetica"
  "color": "#8c1910ff"
  "fontcolor": "#8c1910ff"
  "penwidth": "1.2"

node_attr:
  "fixedsize": "true"
  "fontname": "Helvetica"
  "shape": "ellipse"
  "style": "filled"
  "fontcolor": "white"
  "fillcolor": "#8c1910ff"