edge_attr:
  "fontsize": "12"
  "fontname": "monospace"
  "color": "#8c1910ff"
  "fontcolor": "#8c1910ff"
  "penwidth": "1.2"

node_attr:
  "fixedsize": "true"
  "fontname": "monospace"
  "shape": "box"
  "style": "filled"
  "fontcolor": "white"
  "fillcolor": "#8c1910ff"
  "rank": "same"
  "align": "top"
